# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.7
notifications:
  email: false

install:
    - pip --version
    - pip install -U sphinx
    - pip install --user travis-sphinx

script:
    - travis-sphinx build --branches documents

after_success:
    - travis-sphinx deploy --branches documents