language: python - "3.7"

# before_install will simply setup a conda enviroment for installing python packages, if you
# have project dependencies it's usually recommended to go this route

install:
    - pip install -U sphinx
    - pip install -r requirements.txt
    - pip install --user travis-sphinx

script:
    - travis-sphinx build --branches documents

after_success:
    - travis-sphinx deploy --branches documents