# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.7
notifications:
  email: false

install:
    - pip --version
    - pip install -r requirements.txt
    - pip install -U sphinx

script:
    - cd docs
    - sphinx-apidoc -o . .. -f
    - make html


after_success:
  - ./push.sh