# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.7
notifications:
  email: false

install:
    - pip --version
    - pip install -r requirements.txt
    - pip install -U sphinx
    - pip install travis-sphinx
    - export PATH=$HOME/.local/bin:$PATH

script:
    - travis-sphinx build --source=docs

after_success:
    - travis-sphinx deploy --branches documents